services:
  redis:
    container_name: coupon-redis
    image: redis:7.2.4-alpine
    command: ["redis-server", "--port", "6380"]
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "6380:6380"

  mysql:
    container_name: coupon-mysql
    image: mysql:8.3.0
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp=1
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: coupon
      MYSQL_ROOT_PASSWORD: root
      TZ: UTC
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d